routes/web.php
<?php

use App\Http\Controllers\Admin\CohortController;
use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'welcome'])->name('welcome');

Route::middleware(['auth:sanctum', 'verified'])->group( function () {
    Route::get('/dashboard', [HomeController::class, 'dashboard'])->name('dashboard');
    Route::get('/profile', [HomeController::class, 'profile'])->name('profile');

    // Admin Routes
    Route::group(['prefix' => 'admin'], function () {
        Route::get('/', [DashboardController::class, 'dashboard'])->name('admin.dashboard');
        Route::resource('users', UserController::class);
        Route::resource('cohorts', CohortController::class);
        Route::resource('courses', CourseController::class);

        Route::resource('calendar', CalendarController::class);

        Route::prefix('attendance')->group(function () {
            Route::get('/', [DashboardController::class, 'dashboard'])->name('attendance_dashboard');
        });

        Route::group(['prefix' => 'wizard'], function() {
            Route::get('user', [\App\Http\Controllers\Admin\WizardController::class , 'userCreationWizard'])->name('user_wizard');
            Route::get('cohort', [\App\Http\Controllers\Admin\WizardController::class , 'cohortCreationWizard'])->name('cohort_wizard');
            Route::get('course', [\App\Http\Controllers\Admin\WizardController::class , 'courseCreationWizard'])->name('course_wizard');
        });
    });

    Route::get('testing', function() {
        return Auth::user()->profile_photo_url;
    });

});

resources/views/admin/cohort_manager/create.blade.php
@extends('layouts.backend')

@section('title', 'Index')

@section('content')
<div class="card">
    <div class="card-header">
        <h4>Create</h4>
    </div>

    <div class="card-body">
        <form action="{{ route('cohorts.store') }}" method="post">
            @csrf
            Name
            <input name="name" type="text">
            Status
            <input name="status" type="text">
            Start Date
            <input name="start_date" type="text">
            End Date
            <input name="end_date" type="text">

            <input type="submit">
        </form>

        Creation Forms
        '' 1 Create Cohort
        '' 4 Associate Courses
        '' 4 Import Users
        '' 5 Activate Cohort
        '' 6 Administer Cohort
    </div>
    <livewire:counter />
</div>
@endsection

resources/views/admin/cohort_manager/edit.blade.php
@extends('layouts.backend')

@section('title', 'Index')

@section('content')
<div class="card">
    <div class="card-header">
        <h4>Edit</h4>
    </div>

    <div class="card-body">
            {{ $cohort->name }}
            {{ $cohort->start_date }}
            {{ $cohort->end_date }}
            {{ $cohort->status_id }}
            {{ $cohort->modification_lock }}
    </div>

    <livewire:counter />
</div>
@endsection

resources/views/admin/cohort_manager/index.blade.php
@extends('layouts.backend')

@section('title', 'Index')

@section('content')
    <div class="section-header">
        <h1>Cohort Manager</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="col-3">
                            <h4>Cohort Manager</h4>
                        </div>
                        <div class="col-6">
                            <div class="card-header-form">
                                <form>
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Search">
                                        <div class="input-group-btn">
                                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="col-3">
                            <a href="#" class="btn btn-icon icon-left btn-primary" data-toggle="modal" data-target="#exampleModal"><i class="fal fa-plus"></i> Create New Cohort</a>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <tr>
                                    <th>Name</th>
                                    <th>Start Date</th>
                                    <th>End Date</th>
                                    <th>Status</th>
                                    <th>Enrollment Count</th>
                                    <th>Action</th>
                                </tr>
                                @foreach($cohorts as $cohort)
                                    <tr>
                                        <td>{{ $cohort->name }}</td>
                                        <td>{{ $cohort->start_date }}</td>
                                        <td>{{ $cohort->end_date }}</td>
                                        <td>
                                            @include('shorthand.StatusSwitch', [ $status_id = $cohort->status_id ])
                                        </td>
                                        <td>1</td>
                                        <td><a href="{{ route('cohorts.show', $cohort->id) }}" class="btn btn-secondary">Edit</a></td>
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('modals')
    <div class="modal fade" tabindex="-1" role="dialog" id="exampleModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Create New Cohort</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer bg-whitesmoke br">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/cohort_manager/show.blade.php
@extends('layouts.backend')

@section('title', 'Index')

@section('content')
    <div class="section-header">
        <h1>{{ $cohort->name }} | Cohort Overview</h1>
    </div>
    <div class="section-body">
        <div class="section">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="card card-statistic-2">
                        <div class="card-stats">
                            <div class="card-stats-title">Quick Statistics</div>

                            <div class="card-stats-items">
                                <div class="card-stats-item">
                                    <div class="card-stats-item-label">Start Date</div>
                                    <div class="card-stats-item-count">{{ $cohort->start_date }}</div>
                                </div>
                                <div class="card-stats-item">
                                    <div class="card-stats-item-label">End Date</div>
                                    <div class="card-stats-item-count">{{ $cohort->end_date }}</div>
                                </div>
                                <div class="card-stats-item">
                                    <div class="card-stats-item-label">Status</div>
                                    <div class="card-stats-item-count">{{ $cohort->status_id }}</div>
                                </div>
                            </div>
                        </div>

                        <div class="card-icon shadow-primary bg-primary">
                            <i class="fas fa-users"></i>
                        </div>
                        <div class="card-wrap">
                            <div class="card-header">
                                <h4>Total Students Enrolled</h4>
                            </div>
                            <div class="card-body mb-3">
                                {{ $cohort->student_count }}
                            </div>
                            <div class="card-footer bg-whitesmoke text-right">
                                Footer Card
                            </div>
                        </div>
                    </div>

                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="card">
                        <div class="card-header">
                            <h4>Courses</h4>
                            <div class="card-header-form">
                                <form>
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Search">
                                        <div class="input-group-btn">
                                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <tr>
                                        <th>Name</th>
                                        <th>Number</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                    @foreach ($cohort->courses as $course)
                                        <tr>
                                            <td>{{ $course->name }}</td>
                                            <td>{{ $course->course_number }}</td>
                                            <td>
                                                @include('shorthand.StatusSwitch', [ $status_id = $course->status_id ])
                                            </td>
                                            <td><a href="#" class="btn btn-secondary">Edit</a></td>
                                        </tr>
                                    @endforeach
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Accounts Associated</h4>
                            <div class="card-header-form">
                                <form>
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Search">
                                        <div class="input-group-btn">
                                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <tr>
                                        <th>Avatar</th>
                                        <th>BOCES ID</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Phone Number</th>
                                        <th>Type</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                    @foreach($cohort->users as $user)
                                        <tr>
                                            <td>
                                                <img alt="image" src="{{ $user->avatar_url }}" class="rounded-circle" width="35" data-toggle="tooltip" title="Wildan Ahdian">
                                            </td>
                                            <td>{{ $user->boces_id }}</td>
                                            <td>{{ $user->name }}</td>
                                            <td>{{ $user->email }}</td>
                                            <td>{{ $user->phone_number }}</td>
                                            <td>{{ $user->administrator_level }}</td>
                                            <td>
                                                @include('shorthand.StatusSwitch', [ $status_id = $user->status_id ])
                                            </td>
                                            <td><a href="#" class="btn btn-secondary">Edit</a></td>
                                        </tr>
                                    @endforeach
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <livewire:counter />
</div>
@endsection